server:
  port: 8082

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/ead_course?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
ead:
  api:
    url:
      user: 'http://localhost:8087'




