server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
spring:
  application:
    name: ead-course-service
  datasource:
    url:  jdbc:mysql://localhost:3306/ead_course_v2?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: ${RABBIT_MQ_URL}

ead:
  api:
    url:
      user: 'http://ead-authuser-service/ead-authuser/'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost






